spring:
  profiles:
    #active: test
    active: prod
    #active: dev
  application:
    name: project-Providers
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true